[theme]
base = "light"
primaryColor = "#FF2800"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans-serif"

[client]
toolbarMode = "minimal"

[server]
fileWatcherType = "none"
runOnSave = false
